// Some Actions
export const FETCH_SOMETHING_REQUEST_TRIGGERED = 'FETCH_SOMETHING_REQUEST_TRIGGERED';
export const FETCH_SOMETHING_REQUEST_SUCCESS = 'FETCH_SOMETHING_REQUEST_SUCCESS';
export const FETCH_SOMETHING_REQUEST_FAILURE = 'FETCH_SOMETHING_REQUEST_FAILURE';
